#!/usr/bin/perl

$cutoff = $ARGV[0];

open (LAST, "tail -n 300000 /mnt/index/we-14/indexed_files.db|") || die;
while (<LAST>) {
    chop;
    s/\./\//g;
    $lasts{"/var/spool/news/articles/$_"} = 1;
}
close LAST;

open (TAIL, "tail -n 300000 -f /tmp/history|") || die;

$found = 0;

while (<TAIL>) {
    chop;
    ($time, $file) = split;
    if ($cutoff) {
	if ($time gt $cutoff) {
	    $found = 1;
	}
    } else {
	if (! $found && ! $lasts{$file}) {
	    $found = 1;
	}
    }
    if ($found && ! $lasts{$file}) {
	next if $file =~ /spam/;
	next if $file =~ /gmane.config/;
	next unless $file =~ /^.var.spool.news.articles.gmane\/.*$/;
	$file = "$file";
	print "$_\n";
	$odir = $file;
	$odir =~ s/[0-9]+$//;
	next if -e "${odir}.noindex";
	if (-e $file) {
	    if (open (FILE, $file)) {
		$spam = 0;
		while (<FILE>) {
		    chop;
		    $spam = 1 if /^Xref.*gmane.spam.detected/i;
		    if (! -e "${odir}.ignore-x-no-archive") {
			$spam = 1 if /^x-no-archive:/i;
			$spam = 1 if /^x-archive:/i;
		    }
		    last if /^$/;
		}
		close FILE;
		if (! $spam) {
		    print "Indexable.\n";
		    system("echo 'index $file' | nc finn 8010 2>&1 >>/tmp/index.log");
		    #sleep(1);
		    if (! ($nii++ % 100)) {
			sleep(1);
		    }
		}
	    }
	}
    }
}
